### ISSUE TITLE
Implement text

### ISSUE THREAD

**Issue by tannewt** [adafruit/Adafruit_CircuitPython_framebuf#1]
From https://github.com/adafruit/Adafruit_CircuitPython_SSD1306/issues/2:

Not possible to print text in circuitpython to Feather M0 express with SSD1306 oled shield

```>>> import adafruit_ssd1306 as ssd1306
>>> from board import *
>>> import busio
>>> i2c = busio.I2C(SCL, SDA)
>>> oled = ssd1306.SSD1306_I2C(128, 32, i2c)
>>> oled.fill(0)
>>> oled.show()
>>> oled.text('Hello', 0, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_ssd1306/ssd1306.py", line 102, in text
TypeError: function takes 1 positional arguments but 5 were given
>>>
```

It looks like the framebuf.mpy is not fully implemented.

**Comment by ladyada** [comment]
i did it in latest PR
